### ISSUE TITLE
Is there a LADSPA version?

### ISSUE THREAD

**Issue by LordHelmchen666** [trummerschlunk/master_me#105]
I would like to use master_me with Azuracast https://github.com/AzuraCast/AzuraCast. Liquidsoap used in this project currently only support Ladspa. Maybe in the future there will be LV2 support.
https://github.com/AzuraCast/AzuraCast/discussions/6191

**Comment by magnetophon** [comment]
You can use the faust code to generate a LADSPA plugin:

```
git clone https://github.com/trummerschlunk/master_me.git
cd master_me
faust2ladspa master_me.dsp
```

**Comment by LordHelmchen666** [comment]
Thank you very much! But i get an error
`master_me.dsp : 485 : ERROR : undefined symbol : onePoleSwitching`

**Comment by magnetophon** [comment]
You need a newer faust version.
See: https://github.com/trummerschlunk/master_me/issues/91#issuecomment-1259849367

**Comment by LordHelmchen666** [comment]
Thanks. I got it working now. Now i have to test it with Azuracast.

**Comment by LordHelmchen666** [comment]
Got it working with Azuracast. :-) https://github.com/AzuraCast/AzuraCast/discussions/6191#discussioncomment-5573003

**Comment by BusterNeece** [comment]
@trummerschlunk Thank you to you and the other contributors for your contributions to this project. It's exactly what our users have been wanting: a free and open-source mastering tool that offers extreme customizability in a performant package and adds that extra "polish" to radio broadcasts.

We've incorporated the LADSPA compilation step into our own Docker image build process (as about 95% of our self-hosted user base uses our prebuilt Docker image). After some initial testing from our "power user" community, we hope to be able to build it into our UI so station operators can pick from presets and customize their station sound directly from our web interface.

**Comment by trummerschlunk** [comment]
@BusterNeece Wow, this is great!!
Thank you so much for your message - I am very happy, master_me finds it's way to the right places.

Many years ago, I was briefly working for the Bavarian Broadcast in Munich, Germany setting up a new station for young listeners and one of the most fun and also critical parts was tweaking the broadcast compressor so that both listeners would have a smooth listening experience and the dynamics of the music would not be destroyed.

I am pretty sure that master_me will do a nice job at this ;)

Let us know, how it goes and if you need any help from our side.
