### ISSUE TITLE
level meters are mono

### ISSUE THREAD

**Issue by falkTX** [trummerschlunk/master_me#14]
More like a question, not sure if this is intentional or not but currently seems all meters are mono.
Is this on purpose?

**Comment by trummerschlunk** [comment]
yes, loudness metering has a mono readout in the end. All channels are filtered, weighted and summed for measurement.

Maybe I should have a stereo peak meter for IN and OUT... 

In the modules `limiter` and `brickwall` I am actually not sure, why it's a mono meter for gain reduction. Probably because the channels are linked.
