### ISSUE TITLE
side eq

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#27]
I implemented a 'side eq'.

desired function: boost on the side signal in an area (width) around a center frequency (eq side freq) by an amount in dB (eq side gain)

It's done with a bandpass filter added to the source signal.

1. I am having trouble calculating the loudness of the bandpass so it feels like a parametric eq. (0 adds nothing, +x adds x db)

2. My from width to low and high frequency of the bandpass is messy and broken in low frequencies.

Help needed...

**Comment by magnetophon** [comment]
When you asked me in the chat, I led you down the wrong path.
The proper way to do it, is:
```faust
band_shelf(freq1 ,freq2 ,gain) = fi.low_shelf(0-gain,freq1): fi.low_shelf(gain,freq2)
```
Thanks to @x42 For [the idea](https://gist.github.com/x42/eeb2aa9f9cc4a9083fb2cf2d86645c9a#file-mcomp-dsp-L12)!

If you want differently shaped shelves, look [in the libs](https://github.com/grame-cncm/faustlibraries/blob/master/filters.lib#L2104).

**Comment by x42** [comment]
Keep in mind that this does not work generally, and you need to match the shape (quality).

Also for the case at hand, where the filters is periodically modified (gain changes every sample)  SVF are preferred since they are very stable with all coefficients around 0.  --   For Biquad, and likely even Regalia-Mitra filters internal precision would be required in this use-case.

**Comment by x42** [comment]
If you do want to get scientific about it.. [x42-meters](https://github.com/x42/meters.lv2/) includes a "Stereo/Frequency Scope" :)

![image](https://user-images.githubusercontent.com/30246/185261277-bc915ca6-baeb-4dec-ae24-655df55dd0e4.png)

**Comment by trummerschlunk** [comment]
What I would like to implement is basically this.

`band_shelf(freq1 ,freq2 ,gain) = fi.low_shelf(0-gain,freq1): fi.low_shelf(gain,freq2)` sounds pretty nice to me...

What are SVF? Is there an equivalent in faust?

![image](https://user-images.githubusercontent.com/19374731/185338489-2701c471-cdd5-4c76-a5e4-571acb00b2b5.png)

**Comment by x42** [comment]
> What are SVF? 

https://faustlibraries.grame.fr/libs/filters/#state-variable-filters

**Comment by x42** [comment]
The main benefit of SVF (compared to other filter types) is that they are very stable when automated. 

Also as opposed to biquads they do not require double-precision for low freq filters (where coefficients are close to 1.0 where float precision is a limiting factor).

> Is there an equivalent in faust?

Yes, instead of  `fi.low_shelf(...)` you can use  `fi.svf.ls (...)`.

**Comment by trummerschlunk** [comment]
Thanks @x42 - 'side eq' uses these now.
Would these filters be better for the highpass eq as well?

How is the cpu-cost in comparison?
