### ISSUE TITLE
target slider faster than mouse + double click option for value

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#62]
target slider is still moving faster than the mouse

a double click option for entering the value would be nice

**Comment by falkTX** [comment]
where would the double-click text input appear? on top of the slider? on the bottom text field?

for the movement speed, maybe related to high-dpi? try on a non-high-dpi screen/system if possible for comparison.

**Comment by trummerschlunk** [comment]
text input for target would only be on it's value field

**Comment by trummerschlunk** [comment]
on linux, normal-dpi, vst, reaper: target slider moves slower than mouse

**Comment by falkTX** [comment]
slower than mouse should be fine right? previously I tried to map the position of the mouse 1:1 to slider position, but that gets quite hard to do because the slider has a custom dB scale (to match the meters)

if slower is fine, then both now should be fixed in 9db690233c76628a721dbe8555a398c36ed32c57

btw I dont consider the styling of the text-input box to be final, needs a little tweak so it follows the plugin colors, font size and other bits. but already allows us to test the functionality as it is.

**Comment by trummerschlunk** [comment]
target slider behavior is fine for me now. Closing :)
