### ISSUE TITLE
Too many detections on VirusTotal for the last 64bits release for Windows Platform

### ISSUE THREAD

**Issue by Mastartiq** [trummerschlunk/master_me#96]
This is not normal and can`t be just a mistake, there is a total of 8 detections, one from BitDefender, almost all of them showing the same virus type.
![Detections ](https://user-images.githubusercontent.com/95657491/213464063-69f4f5b5-48fc-4d3e-8587-358f13bcc5a1.png)

What might cause this? I`m just an user, not a developer, so for me that`s a high level of detections, that`s why I opened this issue.

**Comment by nimius-dev** [comment]
False positive.

Only 8 engines detected something, and not those from industry leaders like microsoft, google, sophos or mcaffee.

These false positives can happen when engines are too sensitive regarding certain signatures that can identify viridae (or for scaremongering reasons, since consumer level av is mostly obsolete since windows defender is doing a good job in that regard).

Although possible, it is somewhat unlikely that a collaborative open source projects on github contains a virus since everyone can look into the code and check for themselves. I'm neither involved in this project nor did a full code review (i looked into it a little though) of it but I'm a user of master_me I have zero security concerns.

**Comment by Mastartiq** [comment]
> False positive.
> 
> Only 8 engines detected something, and not those from industry leaders like microsoft, google, sophos or mcaffee.
> 
> These false positives can happen when engines are too sensitive regarding certain signatures that can identify viridae (or for scaremongering reasons, since consumer level av is mostly obsolete since windows defender is doing a good job in that regard).
> 
> Although possible, it is somewhat unlikely that a collaborative open source projects on github contains a virus since everyone can look into the code and check for themselves. I'm neither involved in this project nor did a full code review (i looked into it a little though) of it but I'm a user of master_me I have zero security concerns.

From the list just BitDefender worries me and that all detected the same type of false positive [or not]. I usually read the results, that's why I posted this. The x32bit version is good, I use that. I agree with being obsolete, makes it being picked up as something bad, but in fact it is not, it happens to dragonflyreverb, latest releases, has the same type of detections on virustotal. Thank you for the comment and for the clarifications. Cheers!
